name: Docker Actions

on:
  pull_request:
    types: [first-cat-fact]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: meow
        uses: ./.github/actions/cat-facts
